// src/components/button/button-anchor.svelte
<script lang="ts">
  import Icon from "@iconify/svelte";
  export let label: string;
  export let href: string;
  export let icon: string | null = null;
  export let toBlank = false;

  let className = "w-full text-center px-1";
  if (icon) {
    className = "flex items-center justify-center gap-2 text-center w-full";
  }
</script>

<a class={className} {href} target={toBlank ? "_blank" : "_self"}>
  <span>{label}</span>
  {#if icon}
    <Icon {icon} />
  {/if}
</a>

// src/components/button/button-anchor.tsx
import { cn } from "@/utils/cn";
import { IconType } from "react-icons";

type Props = {
  label: string;
  href: string;
  toBlank?: boolean;
  Icon?: IconType;
};

export default function ButtonAnchor({
  label,
  href,
  toBlank = false,
  Icon,
}: Props) {
  let className = "w-full text-center";
  if (Icon) {
    className = "flex items-center justify-center gap-2 text-center w-full";
  }
  return (
    <a
      className={cn("", className)}
      href={href}
      target={toBlank ? "_blank" : "_self"}
    >
      <span>{label}</span>
      {Icon && <Icon />}
    </a>
  );
}
