// src/components/container/container-root.tsx
import React from "react";
import { cn } from "@/utils/cn";

type Props = {
  variant?: "hero" | "to_top" | "to_bottom";
  isFullScreen?: boolean;
  containerId: string;
  children: React.ReactNode;
};

const ContainerRoot: React.FC<Props> = ({
  variant = "to_bottom",
  isFullScreen = false,
  containerId,
  children,
}) => {
  const heightClass = isFullScreen ? "min-h-screen" : "min-h-full";

  const variantClass = {
    hero: "bg-hero-gradient",
    to_top: "bg-bt-gradient",
    to_bottom: "bg-tb-gradient",
  }[variant];

  return (
    <section
      id={containerId}
      className={cn(
        "flex flex-col justify-center items-center w-full",
        heightClass,
        variantClass,
      )}
    >
      {children}
    </section>
  );
};

export default ContainerRoot;

// src/components/container/container-root.svelte
<script lang="ts">
type Variant = "hero" | "to_top" | "to_bottom";

export let variant: Variant = "to_bottom"
export let isFullscreen = false
export let containerId: string;

const heightClass = isFullscreen ? "min-h-screen" : "min-h-full";

const variantClass = {
  hero: "bg-hero-gradient",
  to_top: "bg-bt-gradient",
  to_bottom: "bg-tb-gradient",
}[variant];
</script>

<section
    id={containerId}
    class={`flex flex-col justify-center items-center w-full ${heightClass} ${variantClass}`}
    >
    <slot/>
</section>
